---
galaxy_info:
  author: Gopichand
  description: "Setup chrooted SFTP service on top of OpenSSH"
  license: MIT
  min_ansible_version: 2.0

  platforms:
  - name: Ubuntu
    versions:
    - all

  galaxy_tags:
    - networking
    - system

dependencies: []
