galaxy_info:
  author: Gopichand
  description: install nodejs with nvm
  license: MIT

  min_ansible_version: 2.0.0

  platforms:
    - name: Ubuntu
      versions:
      - all
    - name: Debian
      versions:
      - all

  galaxy_tags:
    - nodejs
    - nvm

dependencies: []

