galaxy_info:
  author: Gopichand
  description: Enables or disables specified yum plugins
  license: MIT
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
        - 5
        - 6
        - 7
  galaxy_tags:
    - plugin
    - yum
dependencies: []
