galaxy_info:
  author: Gopichand
  description: pass - stores, retrieves, generates, and synchronizes passwords securely

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - system
    - security
    - installer

dependencies: []
