galaxy_info:
  author: Gopichand
  description: An [Ansible](https://www.ansible.com) role to install [Virtualbox](https://www.virtualbox.org/)

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - zesty

  galaxy_tags:
    - virtualization

dependencies: []
