---
dependencies: []

galaxy_info:
  author: gopichand
  description: Simple iptables firewall for most Unix-like systems.
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - networking
    - system
    - security
