---

- name: Create temp directory
  file:
    path: "{{ workstation_tempdir }}"
    state: directory
    mode: 0755

- name: Check for pre-downloaded binary
  stat: path="{{ workstation_tempdir }}/tryworkstation-linux-64.sh"
  register: file_stats

- name: Download workstation
  get_url:
    url: "{{ workstation_download_url }}"
    dest: "{{ workstation_tempdir }}/tryworkstation-linux-64.sh"
  when: not file_stats.stat.exists

- name: Mark script executable
  file:
    path: "{{ workstation_tempdir }}/tryworkstation-linux-64.sh"
    state: file
    mode: 0755

- name: Run installer
  shell: >
    {{ workstation_tempdir }}/tryworkstation-linux-64.sh --eulas-agreed --console
    --required {{'--set-setting vmware-workstation serialNumber '+ workstation_license if workstation_license is defined else '' }}
  args:
    creates: /usr/bin/vmware
  become: yes
  tags:
    - skip_ansible_lint

- name: Install packages needed by vmware packer build
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ workstation_extra_packages }}"