---
galaxy_info:
  author: Gopi chand
  description: installs and configures git
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 23
        - 24
        - 25
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: Alpine
      versions:
        - all

  galaxy_tags:
    - development

dependencies: []
  
