---
 - name: TO configure cron on multiple linux based servers
   hosts: all


   pre_tasks:
     - name: Debug message start
       debug:
         msg: "started installing cron on node machines"
 
   roles:
     - gopi.cron
  
   post_tasks:
     - name: Debug message End
       debug:
         msg: "completed installing cron on node machines"

