---

galaxy_info:
  author: Gopichand
  description: C/C++ Compilers and tools, LEAN.

  license: MIT

  min_ansible_version: 1.9.0

  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - system
    - development

dependencies: []
